birthday1 = input("Enter birthday 1 (DD/MM/YYYY): ")
birthday2 = input("Enter birthday 2 (DD/MM/YYYY): ")
birthday3 = input("Enter birthday 3 (DD/MM/YYYY): ")
birthday4 = input("Enter birthday 4 (DD/MM/YYYY): ")
birthday5 = input("Enter birthday 5 (DD/MM/YYYY): ")

print("\n--- Stored Birthdays ---")
print("Birthday 1:", birthday1)
print("Birthday 2:", birthday2)
print("Birthday 3:", birthday3)
print("Birthday 4:", birthday4)
print("Birthday 5:", birthday5)